gamemanager/Controllers/DlcController.cs
using gamemanager.Models;
using gamemanager.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Threading.Tasks;

namespace gamemanager.Controllers
{
    public class DlcController : Controller
    {
        public async Task<IActionResult> Index()
        {
            List<Dlc> data;

            //This row uses setup in the Startup.cs file
            DataContext dc = HttpContext.RequestServices.GetService(typeof(DataContext)) as DataContext;

            //Check for OnlyOwned variables            
            bool ShowOwned = string.IsNullOrEmpty(HttpContext.Session.GetString("ShowOwned")) ? false : (HttpContext.Session.GetString("ShowOwned").ToLower() == "true") ? true : false;

            //Get a list of dlc data
            if (ShowOwned)
            {
                data = dc.GetAllDlc().Where(a => a.Owned == true).ToList();
                data = data.OrderBy(a => a.Name).ToList();
                ViewBag.ShowOwned = "checked";
            }
            else
            {
                data = dc.GetAllDlc().Where(a => a.Owned == false).ToList();
                data = data.OrderBy(a => a.Ranking).ToList();
                ViewBag.ShowOwned = "";
            }

            //get owned games to populate parent game list
            List<GameEntry> games = dc.GetAllGames().Where(a => a.Owned == true).ToList();
            List<DlcViewModel> dlcViewModel = new List<DlcViewModel>();


            //Update the prices of the games in the list from Steam data
            Code.SteamPriceChecker spc = new Code.SteamPriceChecker();

            foreach (var dlc in data)
            {
                //TODO add support for price checking other stores
                if (dlc.Store != "steam")
                    continue;

                //get current price from steam
                var appid = dc.GetDlcAppId(dlc.Name);
                if (appid == 0) continue;
                var price = await spc.GetPrice(appid.ToString());
                dlc.Price = price;

                //update price in db and throw error if cannot
                if (!dc.EditDlc(dlc))
                {
                    throw new Exception("There was a problem editing the game");
                }
            }

            //assign to list of view models and get the parent game names
            foreach (var dlc in data)
            {
                var parentGame = games.Where(a => a.Id == dlc.ParentGameId).FirstOrDefault();

                DlcViewModel dlcvm = new DlcViewModel()
                {
                    Id = dlc.Id,
                    Name = dlc.Name,
                    Notes = dlc.Notes,
                    Owned = dlc.Owned,
                    ParentGameId = dlc.ParentGameId,
                    ParentGameName = parentGame.Name,
                    Price = dlc.Price,
                    Ranking = dlc.Ranking,
                    Rating = dlc.Rating,
                    Store = dlc.Store
                };

                dlcViewModel.Add(dlcvm);
            }
            
            //sort list by ranking
            dlcViewModel = dlcViewModel.OrderBy(a => a.Ranking).ToList();

            //Assign any message to the viewbag      
            string message = HttpContext.Session.GetString("Message");
            ViewBag.Message = message;

            //Clear message out so it's not shown multiple times
            HttpContext.Session.Remove("Message");            

            //Pass list to the view as Model
            return View(dlcViewModel);
        }

        [HttpGet]
        public IActionResult RankChange(int id, bool increase)
        {
            //This row uses setup in the Startup.cs file
            DataContext dc = HttpContext.RequestServices.GetService(typeof(DataContext)) as DataContext;

            var dlc = dc.GetDlc(id);
            bool outcomeOfEdit = false;
            bool outcomeOfOtherEdit = false;

            if (dlc != null)
            {
                if (increase)
                {
                    dlc.Ranking--;

                    //Get the game that is already in the new position, and move it the opposite way
                    var otherDlc = dc.GetDlcByRanking(dlc.Ranking);

                    if (otherDlc != null)
                    {
                        otherDlc.Ranking++;
                        outcomeOfOtherEdit = dc.EditDlc(otherDlc);

                        if (!outcomeOfOtherEdit)
                        {
                            throw new Exception("Error editing other item");
                        }
                    }
                }
                else
                {
                    dlc.Ranking++;

                    //Get the game that is already in the new position, and move it the opposite way
                    var otherDlc = dc.GetDlcByRanking(dlc.Ranking);

                    if (otherDlc != null)
                    {
                        otherDlc.Ranking--;
                        outcomeOfOtherEdit = dc.EditDlc(otherDlc);

                        if (!outcomeOfOtherEdit)
                        {
                            throw new Exception("Error editing other item");
                        }
                    }
                }

                outcomeOfEdit = dc.EditDlc(dlc, true);
            }

            if (!outcomeOfEdit) HttpContext.Session.SetString("Message", "Problem changing rank");
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int Id)
        {
            //This row uses setup in the Startup.cs file
            DataContext dc = HttpContext.RequestServices.GetService(typeof(DataContext)) as DataContext;

            bool outcomeOfDelete = dc.DeleteDlc(Id);

            if (outcomeOfDelete) HttpContext.Session.SetString("Message", "Dlc deleted");

            return RedirectToAction("Index");
        }

        public IActionResult AddDlc(int Id)
        {
            DlcViewModel dlc = new DlcViewModel() { ParentGameId = Id };
            return View(dlc);
        }

        public IActionResult ViewDlc(int Id)
        {
            //This row uses setup in the Startup.cs file
            DataContext dc = HttpContext.RequestServices.GetService(typeof(DataContext)) as DataContext;

            GameEntry g = dc.GetGame(Id);
            g.Dlc = dc.GetDlcForGame(Id);

            return View(g);
        }

        public IActionResult OnlyOwned(bool status)
        {
            HttpContext.Session.SetString("ShowOwned", status.ToString());

            return RedirectToAction("Index");
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Save(DlcViewModel dlc)
        {
            //This row uses setup in the Startup.cs file
            DataContext dc = HttpContext.RequestServices.GetService(typeof(DataContext)) as DataContext;

            bool outcomeOfSave = dc.EditDlc((Dlc)dlc, true);

            if (outcomeOfSave) HttpContext.Session.SetString("Message", "Record Saved");

            return RedirectToAction("Index");
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult SaveNewDlc(DlcViewModel dlc)
        {
            //This row uses setup in the Startup.cs file
            DataContext dc = HttpContext.RequestServices.GetService(typeof(DataContext)) as DataContext;

            if (ModelState.IsValid)
            {
                if (dlc.Ranking == 0)
                {
                    try
                    {
                        dlc.Ranking = short.Parse(dc.GetNextRanking(Code.ItemType.Dlc));
                    }
                    catch (System.Exception ex)
                    {
                        HttpContext.Session.SetString("Message", "Error trying to get next available rank: " + ex.Message);
                        return RedirectToAction("Index");
                    }
                }

                bool outcomeOfSave = dc.InsertDlc(dlc);

                if (outcomeOfSave)
                {
                    HttpContext.Session.SetString("Message", "Record Saved");

                    //get game id
                    var dbGame = dc.GetDlcByName(dlc.Name);

                    //add a new store data entry for this game
                    if (!dc.InsertStoreDataDlcEntry(dbGame.Id, dlc.StoreUrl))
                    {
                        HttpContext.Session.SetString("Error", "There was a problem entering store data for game");
                    }
                }

                return RedirectToAction("Index");
            }
            else
            {
                //repopulate list of games to populate the parent game dropdown list
                var games = dc.GetAllGames().Select(g => (g.Id, g.Name)).ToList();

                //assign the list of possible parent games to the games property of the vm
                foreach (var (Id, Name) in games)
                {
                    dlc.PotentialParentGames.Add(new SelectListItem(Name, Id.ToString()));
                }
                return View("New", dlc);
            }
        }

        public IActionResult Edit(int id)
        {
            //This row uses setup in the Startup.cs file
            DataContext dc = HttpContext.RequestServices.GetService(typeof(DataContext)) as DataContext;

            //Get the game that relates to the id provided
            var data = dc.GetDlc(id);

            DlcViewModel dlcvm = new DlcViewModel(data);

            var storeData = dc.GetDlcStoreData(id);


gamemanager/Views/Home/Edit.cshtml
@model gamemanager.ViewModels.GameViewModel
@{
    ViewData["Title"] = "Edit game";
}

<h1>Edit game</h1>


<form asp-action="Save" method="post">
    <div>
        <label asp-for="Id"></label>
        <input asp-for="Id" readonly />
    </div>
    <div>
        <label asp-for="Name"></label>
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <div>
        <label asp-for="Genre"></label>
        <input asp-for="Genre" />
        <span asp-validation-for="Genre"></span>
    </div>
    <div>
        <label asp-for="Price"></label>
        <input asp-for="Price" />
        <span asp-validation-for="Price"></span>
    </div>
    <div>
        <label asp-for="Owned"></label>
        <input asp-for="Owned" />
        <span asp-validation-for="Owned"></span>
    </div>
    <div>
        <label asp-for="Notes"></label>
        <input asp-for="Notes" />
        <span asp-validation-for="Notes"></span>
    </div>
    <div>
        <label asp-for="Rating"></label>
        <input asp-for="Rating" />
        <span asp-validation-for="Rating"></span>
    </div>
    <div>
        <label asp-for="Ranking"></label>
        <input asp-for="Ranking" />
        <span asp-validation-for="Ranking"></span>
    </div>
    <div>
        <label asp-for="Store"></label>
        <input asp-for="Store" />
        <span asp-validation-for="Store"></span>
    </div>
    <div>
        <label asp-for="StoreUrl"></label>
        <input asp-for="StoreUrl" />
        <span asp-validation-for="StoreUrl"></span>
    </div>
    @Html.AntiForgeryToken()
    <div>
        <input type="submit" value="Save" />
    </div>
</form>

gamemanager/Views/Home/Index.cshtml
@model List<gamemanager.Models.GameEntry>

@{
    ViewData["Title"] = "Home Page";
}

<div class="container container-content">

    @{//check for message in viewbag
        string message = ViewBag.Message == null ? string.Empty : ViewBag.Message;}

    @if (!string.IsNullOrEmpty(message))
    {
        <div class="alert alert-primary">
            <strong>Message</strong> @message
        </div>
    }

    <div class="row">

        <div class="form-check">
            <label class="form-check-label">
                <input type="checkbox" class="form-check-input showOwnedCB" name="showOwned" id="showOwned" value="" @ViewBag.ShowOwned>Show owned games
            </label>
        </div>

    </div>

    <div class="row">
        <div class="table table-striped">
            <table>
                <thead>
                    <tr>
                        <th></th>
                        <th>Rank</th>
                        <th>Name</th>
                        <th>Genre</th>                        
                        <th>Price</th>                       
                        <th>Store</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        @foreach (var item in Model)
                        {
                            var computedRanking = item.Owned ? "N/A" : item.Ranking.ToString();
                            var computedPrice = item.Owned ? "N/A" : (item.Price == 0) ? "N/A" : item.Price.ToString();
                            var computedOwnership = item.Owned ? "Yes" : "No";
                            var computedRating = item.Owned ? item.Rating.ToString() : "N/A";
                    <tr>
                        <td>
                            @if (computedRanking != "N/A")
                            {
                                if (item.Ranking != Model.Count)
                                {
                                    <a href="@Url.Action("RankChange", "Home", new { id = item.Id, increase = false })"><img src="~/resources/arrow_down.png" width="20" height="20" class="d-inline" /></a>
                                }
                                else
                                {
                                    <img src="~/resources/arrow_down_hollow.png" width="20" height="20" class="d-inline" />
                                }

                                if (item.Ranking != 1)
                                {
                                    <a href="@Url.Action("RankChange", "Home", new { id = item.Id, increase = true })"><img src="~/resources/arrow_up.png" width="20" height="20" class="d-inline" style="margin-right:2px;" /></a>
                                }
                                else
                                {
                                    <img src="~/resources/arrow_up_hollow.png" width="20" height="20" class="d-inline" style="margin-right:2px;" />
                                }

                            }
                        </td>
                        <td>@computedRanking</td>
                        <td>@item.Name</td>
                        <td>@item.Genre</td>
                        <td>@computedPrice</td>
                        <td>
                            @switch (item.Store)
                            {
                                case "steam":
                                    <img src="~/resources/steam.png" width="20" height="20" class="d-inline" />
                                    break;
                                case "epic":
                                    <img src="~/resources/epic.png" width="20" height="20" class="d-inline" />
                                    break;
                                case "uplay":
                                    <img src="~/resources/Uplay.png" width="20" height="20" class="d-inline" />
                                    break;
                                case "humble":
                                    <img src="~/resources/humble.png" width="20" height="20" class="d-inline" />
                                    break;
                                default:
                                    break;
                            }
                        </td>
                        <td>
                            <button class="btn btn-secondary" onclick="location.href='@Url.Action("Edit", "Home", new { id = item.Id })'" title="Edit" value="Edit">Edit</button>
                            <button class="btn btn-secondary" onclick="location.href='@Url.Action("ViewDlc", "Dlc", new { id = item.Id })'" title="ViewDlc" value="ViewDlc">View Dlc</button>
                            <button class="btn btn-secondary" onclick="window.confirm('Are you sure?'); location.href='@Url.Action("Delete", "Home", new { id = item.Id })'" title="Delete" value="Delete">Delete</button>
                        </td>
                    </tr>

                        }
                    </tbody>
                </table>
            </div>
        </div>

        <div class="row">
            <div class="col-12"><button class="btn btn-primary" onclick="location.href='@Url.Action("New", "Home")'" title="New" value="New">New Game</button></div>
        </div>

    </div>

    <script src="~/js/PageScripts/home.js"></script>

gamemanager/Views/Home/New.cshtml
@model gamemanager.ViewModels.GameViewModel

@{
    ViewData["Title"] = "New Game";
}

<h1>Add new game</h1>

<form asp-action="SaveNew" method="post">
    <div>
        <input asp-for="Id" readonly hidden />
    </div>
    <div>
        <label asp-for="Name"></label>
        <input asp-for="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Genre"></label>
        <input asp-for="Genre" />
        <span asp-validation-for="Genre" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Price"></label>
        <input asp-for="Price" />
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Owned"></label>
        <input asp-for="Owned" />
        <span asp-validation-for="Owned" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Notes"></label>
        <input asp-for="Notes" />
        <span asp-validation-for="Notes" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Rating"></label>
        <input asp-for="Rating" />
        <span asp-validation-for="Rating" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Ranking"></label>
        <input asp-for="Ranking" />
        <span asp-validation-for="Ranking" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Store"></label>
        <input asp-for="Store" />
        <span asp-validation-for="Store"></span>
    </div>
    <div>
        <label asp-for="StoreUrl"></label>
        <input asp-for="StoreUrl" />
        <span asp-validation-for="StoreUrl"></span>
    </div>
    @Html.AntiForgeryToken()
    <div>
        <input type="submit" value="Save" />
    </div>
</form>
